#!/bin/bash

echo "Integration Test ..."


echo "Starting Server ..."
../build/bin/main ../tests/example_config &
curl -i -s http://localhost:8080 -o curl_resp.txt -m 3

echo "Shutting Down Server ..."
pkill -f main 

diff -s ./curl_resp.txt ./verify_resp.txt &>/dev/null
if [ $? -eq 0 ]
then
    echo "Integration Test Passed."
fi
exit $?
